### PR TITLE
flag extension for safe parallel read/write when using sphinx -j flag

### PR DESCRIPTION
**Pull request by CagtayFabry**
I think this should be what's needed for #16  (in case the extension is indeed safe)

### CODE REVIEW

**Comment by pllim** [comment]
Thanks! If this works, probably needs a new release as well.

**Comment by eslavich** [comment]
I built the asdf-standard docs with this branch and `-j 5` and didn't notice any issues in the output.  The test failures look unrelated, I'll file an issue to fix them in a separate PR.

**Review by eslavich — APPROVED** [review]
LGTM, thanks!

**Comment by CagtayFabry** [comment]
> I built the asdf-standard docs with this branch and `-j 5` and didn't notice any issues in the output. The test failures look unrelated, I'll file an issue to fix them in a separate PR.

thanks for checking
I did run Sphinx (v3.2.1) with `-W` so otherwise this would probably just throw a warning (

**Comment by marscher** [comment]
It would be great, if this patch could be included and released soon! Thank you very much :)

**Comment by eslavich** [comment]
It seems like this is intended to be a fork and not merged into asdf-format/sphinx-asdf?  I see some weldx-specific code in here...

**Comment by CagtayFabry** [comment]
Sorry I'm actually not sure why that last commit/merge happened.. I'll clean this up

**Comment by CagtayFabry** [comment]
moved to #27

**Pull request closed without merging**
