### PR TITLE
add 'tag' parsing

### PR DESCRIPTION
**Pull request by CagtayFabry**
After using `tag` in place of `$ref` more often ([see asdf#814](https://github.com/asdf-format/asdf/issues/814#issuecomment-650255706)) I started to miss seeing the reference (+hyperlink) in the `sphinx-asdf` output that gets generated from `$ref`

Without going into details of the `sphinx-asdf` code I implemented a few snippets that (hopefully) parse the `tag` keywords similar to `$ref`. Some small examples I ran looked the way I expected.
Something like this:
```yaml
definitions:
  root-gap:
    description: |
      Root gap
    tag: "tag:stsci.edu:asdf/unit/quantity-1.1.0"
    wx_unit: "mm"
```

Could this be added to `sphinx-asdf`?

### CODE REVIEW

**Comment by eslavich** [comment]
Given that we're planning to allow wildcard patterns in the tag validator, is a link appropriate here?  Or would we link only if there's no asterisk character in the tag value?

**Comment by CagtayFabry** [comment]
> Given that we're planning to allow wildcard patterns in the tag validator, is a link appropriate here? Or would we link only if there's no asterisk character in the tag value?

The glob asterisk sure breaks the link here so imo it seems reasonable to remove it in this case.
I did not want to fiddle with what `_create_reference` actually does, just get rid of the `This node has no type definition (unrestricted)` line when using the `tag` validator 😉

**Comment by CagtayFabry** [comment]
> Given that we're planning to allow wildcard patterns in the tag validator, is a link appropriate here? Or would we link only if there's no asterisk character in the tag value?

I have removed the link in case `tag` is defined with any kind of asterisk usage @eslavich

**Comment by eslavich** [comment]
Okay, thanks!  Sorry for the delay, I need to either locate someone with the expertise to review this or learn something about the package myself.  I'll bring it up at our morning meeting.

**Comment by CagtayFabry** [comment]
> Okay, thanks! Sorry for the delay, I need to either locate someone with the expertise to review this or learn something about the package myself. I'll bring it up at our morning meeting.

No hurry. I wasn't sure how much development is going on with `sphinx-asdf`
I am currently messing around to get to know (and adapt) the tool on my own fork for our project over at [weldx](https://github.com/BAMWelDX/weldx) but I thought some more generic `asdf` related things might be interesting for you as as well.

**Review by eslavich — APPROVED** [review]
Thanks, this looks good.  At some point we'll want to use the asdf library to resolve these but that can wait for now.  I'll add an issue so we remember to do that at some point.

**Pull request merged**
