### PR TITLE
add oneOf to list of combiner keywords

### PR DESCRIPTION
**Pull request by CagtayFabry**
I think `oneOf` belongs here with the other combiners or was this left out intentionally?

### CODE REVIEW

**Comment by eslavich** [comment]
That definitely seems like an oversight, thanks!

**Comment by CagtayFabry** [comment]
it works as intended on our fork in case you still want to merge this @eslavich

**Comment by eslavich** [comment]
@CagtayFabry can you rebase onto the latest master?  I'd like to see the tests pass before I merge, and our Travis integration doesn't work anymore.  Rebasing should activate the GitHub Actions tests.

**Comment by CagtayFabry** [comment]
> @CagtayFabry can you rebase onto the latest master?  I'd like to see the tests pass before I merge, and our Travis integration doesn't work anymore.  Rebasing should activate the GitHub Actions tests.

Sure will do later

**Review by eslavich — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
